// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA09oOMVS63J-gyKlk0TyHQDNWuzmbig0Q',
    appId: '1:1057984911405:android:4ad09cf2a4b1e9dd94c0a4',
    messagingSenderId: '1057984911405',
    projectId: 'foodly-flutter-dc94b',
    databaseURL: 'https://foodly-flutter-dc94b-default-rtdb.firebaseio.com',
    storageBucket: 'foodly-flutter-dc94b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxBpSy7vvZYMubU_FiEIsw0P9UaSBHfdM',
    appId: '1:1057984911405:ios:dc39f9f211f07a4b94c0a4',
    messagingSenderId: '1057984911405',
    projectId: 'foodly-flutter-dc94b',
    databaseURL: 'https://foodly-flutter-dc94b-default-rtdb.firebaseio.com',
    storageBucket: 'foodly-flutter-dc94b.appspot.com',
    iosClientId: '1057984911405-8cbk6588p8n330msanv2quje1s9m5h4k.apps.googleusercontent.com',
    iosBundleId: 'com.dbestech.foodlyDriver',
  );
}
